<template>
  <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" version="1.1">
    <title>kpi</title>
    <g id="Layer_1">
      <title>Layer 1</title>
      <line
        stroke="#7f7f7f"
        id="svg_9"
        y2="6"
        x2="21"
        y1="12"
        x1="3"
        fill="none"
      />
      <line
        stroke="#7f7f7f"
        id="svg_10"
        y2="18"
        x2="21"
        y1="12"
        x1="3"
        fill="none"
      />
      <ellipse
        ry="1"
        rx="1"
        id="svg_12"
        cy="10"
        cx="9"
        stroke="#4c4c4c"
        fill="#999999"
      />
      <ellipse
        ry="1"
        rx="1"
        id="svg_13"
        cy="14"
        cx="9"
        stroke="#4c4c4c"
        fill="#999999"
      />
      <ellipse
        ry="1"
        rx="1"
        id="svg_14"
        cy="8"
        cx="15"
        stroke="#4c4c4c"
        fill="#999999"
      />
      <ellipse
        ry="1"
        rx="1"
        id="svg_15"
        cy="16"
        cx="15"
        stroke="#4c4c4c"
        fill="#999999"
      />
      <ellipse
        ry="2"
        rx="2"
        id="svg_8"
        cy="18"
        cx="21"
        stroke="#b2b2b2"
        fill="#b2b2b2"
      />
      <ellipse
        ry="2"
        rx="2"
        id="svg_7"
        cy="6"
        cx="21"
        stroke="#b2b2b2"
        fill="#b2b2b2"
      />
      <ellipse
        ry="2"
        rx="2"
        id="svg_5"
        cy="12"
        cx="3"
        stroke="#b2b2b2"
        fill="#b2b2b2"
      />
    </g>
  </svg>
</template>
