<template>
  <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
    <!-- Created with UXWing SVG Editor - https://uxwing.com/svg-icon-editor/ -->
    <defs>
      <filter id="svg_2_blur" x="-50%" y="-50%" width="200%" height="200%">
        <feGaussianBlur stdDeviation="0.1" />
      </filter>
    </defs>
    <g>
      <title>background</title>
      <rect
        x="-1"
        y="-1"
        width="3.499954"
        height="3.499954"
        id="canvas_background"
        fill="none"
      />
      <g id="canvasGrid" display="none">
        <rect
          id="svg_1"
          width="100%"
          height="100%"
          x="0"
          y="0"
          stroke-width="0"
          fill="url(#gridpattern)"
        />
      </g>
    </g>
    <g>
      <title>Layer 1</title>
      <ellipse
        stroke="#4c4c4c"
        fill="none"
        cx="12"
        cy="12.031249"
        id="svg_2"
        rx="2"
        ry="2"
        filter="url(#svg_2_blur)"
      />
      <line
        stroke="#4c4c4c"
        fill="none"
        stroke-opacity="null"
        fill-opacity="null"
        x1="14.937459"
        y1="12"
        x2="23.687139"
        y2="12"
        id="svg_23"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
      />
      <line
        stroke="#4c4c4c"
        fill="none"
        stroke-opacity="null"
        fill-opacity="null"
        x1="0.750345"
        y1="12"
        x2="9.312532"
        y2="12"
        id="svg_24"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
      />
    </g>
  </svg>
</template>
