<template>
  <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
    <!-- Created with UXWing SVG Editor - https://uxwing.com/svg-icon-editor/ -->
    <defs>
      <filter id="svg_2_blur" x="-50%" y="-50%" width="200%" height="200%">
        <feGaussianBlur stdDeviation="0.1" />
      </filter>
    </defs>
    <g>
      <title>background</title>
      <rect
        x="-1"
        y="-1"
        width="26"
        height="26"
        id="canvas_background"
        fill="none"
      />
      <g id="canvasGrid" display="none">
        <rect
          id="svg_1"
          width="100%"
          height="100%"
          x="0"
          y="0"
          stroke-width="0"
          fill="url(#gridpattern)"
        />
      </g>
    </g>
    <g>
      <title>Layer 1</title>
      <ellipse
        fill="none"
        cx="4.812721"
        cy="12"
        id="svg_2"
        rx="2"
        ry="2"
        filter="url(#svg_2_blur)"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="0.125365"
        y1="12"
        x2="2.375293"
        y2="12"
        id="svg_24"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
        stroke="#4c4c4c"
      />
      <ellipse
        fill="none"
        cx="12.499985"
        cy="12"
        id="svg_38"
        rx="2"
        ry="2"
        filter="url(#svg_2_blur)"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="7.812628"
        y1="12"
        x2="10.062556"
        y2="12"
        id="svg_39"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
        stroke="#4c4c4c"
      />
      <ellipse
        fill="none"
        cx="19.999754"
        cy="12"
        id="svg_40"
        rx="2"
        ry="2"
        filter="url(#svg_2_blur)"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="15.312397"
        y1="12"
        x2="17.562325"
        y2="12"
        id="svg_41"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="23.187155"
        y1="12"
        x2="25.437083"
        y2="12"
        id="svg_42"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke="#4c4c4c"
      />
      <ellipse
        fill="none"
        cx="4.812721"
        cy="4.75"
        id="svg_3"
        rx="2"
        ry="2"
        filter="url(#svg_2_blur)"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="0.125365"
        y1="4.75"
        x2="2.375293"
        y2="4.75"
        id="svg_4"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
        stroke="#4c4c4c"
      />
      <ellipse
        fill="none"
        cx="12.499985"
        cy="4.75"
        id="svg_5"
        rx="2"
        ry="2"
        filter="url(#svg_2_blur)"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="7.812628"
        y1="4.75"
        x2="10.062556"
        y2="4.75"
        id="svg_6"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
        stroke="#4c4c4c"
      />
      <ellipse
        fill="none"
        cx="19.999754"
        cy="4.75"
        id="svg_7"
        rx="2"
        ry="2"
        filter="url(#svg_2_blur)"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="15.312397"
        y1="4.75"
        x2="17.562325"
        y2="4.75"
        id="svg_8"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="23.187155"
        y1="4.75"
        x2="25.437083"
        y2="4.75"
        id="svg_9"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke="#4c4c4c"
      />
      <ellipse
        fill="none"
        cx="4.812721"
        cy="19"
        id="svg_10"
        rx="2"
        ry="2"
        filter="url(#svg_2_blur)"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="0.125365"
        y1="19"
        x2="2.375293"
        y2="19"
        id="svg_11"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
        stroke="#4c4c4c"
      />
      <ellipse
        fill="none"
        cx="12.499985"
        cy="19"
        id="svg_12"
        rx="2"
        ry="2"
        filter="url(#svg_2_blur)"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="7.812628"
        y1="19"
        x2="10.062556"
        y2="19"
        id="svg_13"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
        stroke="#4c4c4c"
      />
      <ellipse
        fill="none"
        cx="19.999754"
        cy="19"
        id="svg_14"
        rx="2"
        ry="2"
        filter="url(#svg_2_blur)"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="15.312397"
        y1="19"
        x2="17.562325"
        y2="19"
        id="svg_15"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke-dasharray="2,2"
        stroke="#4c4c4c"
      />
      <line
        fill="none"
        stroke-width="0.5"
        stroke-opacity="null"
        fill-opacity="null"
        x1="23.187155"
        y1="19"
        x2="25.437083"
        y2="19"
        id="svg_16"
        stroke-linejoin="null"
        stroke-linecap="null"
        stroke="#4c4c4c"
      />
      <rect
        stroke="#4c4c4c"
        opacity="0.85"
        rx="2"
        id="svg_17"
        height="6.75"
        width="23.25"
        y="8.625"
        x="0.375"
        fill-opacity="null"
        stroke-opacity="null"
        stroke-width="0.5"
        fill="none"
      />
    </g>
  </svg>
</template>
