<template>
  <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg">
    <!-- Created with UXWing SVG Editor - https://uxwing.com/svg-icon-editor/ -->
    <defs>
      <filter height="200%" width="200%" y="-50%" x="-50%" id="svg_2_blur">
        <feGaussianBlur stdDeviation="0.1" in="SourceGraphic" />
      </filter>
    </defs>
    <g>
      <title>background</title>
      <rect
        fill="none"
        id="canvas_background"
        height="26"
        width="26"
        y="-1"
        x="-1"
      />
      <g
        display="none"
        overflow="visible"
        y="0"
        x="0"
        height="100%"
        width="100%"
        id="canvasGrid"
      >
        <rect
          fill="url(#gridpattern)"
          stroke-width="0"
          y="0"
          x="0"
          height="100%"
          width="100%"
        />
      </g>
    </g>
    <g>
      <title>Layer 1</title>
      <ellipse
        stroke="#4c4c4c"
        filter="url(#svg_2_blur)"
        ry="2"
        rx="2"
        id="svg_2"
        cy="12"
        cx="4.812721"
        fill="none"
      />
      <line
        stroke="#4c4c4c"
        stroke-dasharray="2,2"
        stroke-linecap="null"
        stroke-linejoin="null"
        id="svg_24"
        y2="12"
        x2="2.375293"
        y1="12"
        x1="0.125365"
        fill-opacity="null"
        stroke-opacity="null"
        stroke-width="0.5"
        fill="none"
      />
      <ellipse
        stroke="#4c4c4c"
        filter="url(#svg_2_blur)"
        ry="2"
        rx="2"
        id="svg_38"
        cy="12"
        cx="12.499985"
        fill="none"
      />
      <line
        stroke="#4c4c4c"
        stroke-dasharray="2,2"
        stroke-linecap="null"
        stroke-linejoin="null"
        id="svg_39"
        y2="12"
        x2="10.062556"
        y1="12"
        x1="7.812628"
        fill-opacity="null"
        stroke-opacity="null"
        stroke-width="0.5"
        fill="none"
      />
      <ellipse
        stroke="#4c4c4c"
        filter="url(#svg_2_blur)"
        ry="2"
        rx="2"
        id="svg_40"
        cy="12"
        cx="19.999754"
        fill="none"
      />
      <line
        stroke="#4c4c4c"
        stroke-dasharray="2,2"
        stroke-linecap="null"
        stroke-linejoin="null"
        id="svg_41"
        y2="12"
        x2="17.562325"
        y1="12"
        x1="15.312397"
        fill-opacity="null"
        stroke-opacity="null"
        stroke-width="0.5"
        fill="none"
      />
      <line
        stroke="#4c4c4c"
        stroke-linecap="null"
        stroke-linejoin="null"
        id="svg_42"
        y2="12"
        x2="25.437083"
        y1="12"
        x1="23.187155"
        fill-opacity="null"
        stroke-opacity="null"
        stroke-width="0.5"
        fill="none"
      />
    </g>
  </svg>
</template>
