# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: alpine:latest
stages:
- automerge
- test
variables:
  ACCEPT: 'Accept: application/json'
  CONTENT_TYPE: 'Content-Type: application/json'
  BEARER: 'Authorization: Bearer ${TEAMCITY_TOKEN}'
Merge_MR_IF_TeamCity_Built:
  stage: automerge
  when: manual
  only:
  #- merge_requests
  tags:
  - docker
  before_script:
  - apk update && apk upgrade
  - apk add --no-cache bash git curl openssh jq
  script:
  - export PR_BRANCH=$(curl -s "https://git.processm.cs.put.poznan.pl/api/v4/projects/${CI_PROJECT_ID}/merge_requests?private_token=${OAUTH_TOKEN}&state=opened"
    | jq -r ".[]|select(.sha == \"${CI_COMMIT_SHA}\")|.source_branch")
  - curl -s -X POST -H "${ACCEPT}" -H "${CONTENT_TYPE}" -H "${BEARER}" -d "{\"branchName\":\"$PR_BRANCH\",
    \"buildType\":{\"id\":\"ProcessM_AutoMergeMr\", \"projectId\":\"ProcessM\"}, \"properties\":{\"property\":[{\"name\":\"mr_iid\",\"value\":\"$CI_MERGE_REQUEST_IID\"},
    {\"name\":\"mr_branch\",\"value\":\"$PR_BRANCH\"}, {\"name\":\"project_id\",\"value\":\"$CI_MERGE_REQUEST_PROJECT_ID\"}]}}"
    "https://build.processm.cs.put.poznan.pl/app/rest/buildQueue"
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
