CREATE TYPE ATTRIBUTE_TYPE AS ENUM ('int', 'float', 'string', 'id', 'boolean', 'list', 'date');
CREATE TYPE SCOPE_TYPE AS ENUM ('event', 'trace');

ALTER TABLE globals
    ALTER COLUMN scope SET DATA TYPE SCOPE_TYPE USING scope::text::SCOPE_TYPE;
ALTER TABLE globals
    ALTER COLUMN type SET DATA TYPE ATTRIBUTE_TYPE USING type::text::ATTRIBUTE_TYPE;

ALTER TABLE classifiers
    ALTER COLUMN scope SET DATA TYPE SCOPE_TYPE USING scope::text::SCOPE_TYPE;

ALTER TABLE logs_attributes
    ALTER COLUMN type SET DATA TYPE ATTRIBUTE_TYPE USING type::text::ATTRIBUTE_TYPE;
ALTER TABLE traces_attributes
    ALTER COLUMN type SET DATA TYPE ATTRIBUTE_TYPE USING type::text::ATTRIBUTE_TYPE;
ALTER TABLE events_attributes
    ALTER COLUMN type SET DATA TYPE ATTRIBUTE_TYPE USING type::text::ATTRIBUTE_TYPE;
