/**
 * Processm
 * Description of api methods used in processm.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package processm.services.api

import io.ktor.server.locations.*
import java.util.*

@KtorExperimentalLocationsAPI
object Paths {
    /**
     * Server-side-stored configuration for GUI.
     */
    @Location("/config")
    class Config

    /**
     * Group
     *
     * @param groupId Group ID
     */
    @Location("/organizations/{organizationId}/groups/{groupId}")
    class Group(val organizationId: UUID, val groupId: UUID)

    /**
     * Members of the specified group
     *
     * @param groupId Group ID
     */
    @Location("/organizations/{organizationId}/groups/{groupId}/members")
    class GroupMembers(val organizationId: UUID, val groupId: UUID)

    /**
     * Groups og the current user&#39;s organization
     *
     */
    @Location("/organizations/{organizationId}/groups")
    class Groups(val organizationId: UUID)

    /**
     * Subgroups of the specified group
     *
     * @param groupId Group ID
     */
    @Location("/organizations/{organizationId}/groups/{groupId}/subgroups")
    class Subgroups(val organizationId: UUID, val groupId: UUID)

    /**
     * Mmber from the specified group
     *
     * @param groupId Group ID
     * @param userId User ID
     */
    @Location("/organizations/{organizationId}/groups/{groupId}/members/{userId}")
    class GroupMember(val organizationId: UUID, val groupId: UUID, val userId: UUID)

    /**
     * Subgroup of a group.
     *
     * @param groupId Group ID
     * @param subgroupId Subgroup ID
     */
    @Location("/organizations/{organizationId}/groups/{groupId}/subgroups/{subgroupId}")
    class Subgroup(val organizationId: UUID, val groupId: UUID, val subgroupId: UUID)

    /**
     * Organization.
     *
     * @param organizationId Organization ID
     */
    @Location("/organizations/{organizationId}")
    class Organization(val organizationId: UUID)

    /**
     * Groups associated with the specified organization.
     *
     * @param organizationId Organization ID
     */
    @Location("/organizations/{organizationId}/groups")
    class OrganizationGroups(val organizationId: UUID)

    /**
     * Members of the specified organization
     *
     * @param organizationId Organization ID
     */
    @Location("/organizations/{organizationId}/members")
    class OrganizationMembers(val organizationId: UUID)

    /**
     * List of organizations
     */
    @Location("/organizations")
    class Organizations

    /**
     * A member of the specified organization
     *
     * @param organizationId Organization ID
     * @param userId User ID
     */
    @Location("/organizations/{organizationId}/members/{userId}")
    class OrganizationMember(val organizationId: UUID, val userId: UUID)

    /**
     * Data stores assigned to [organizationId].
     *
     * @param organizationId Organization ID
     */
    @Location("/organizations/{organizationId}/data-stores")
    class DataStores(val organizationId: UUID)

    /**
     * Logs stored in [dataStoreId].
     *
     * @param dataStoreId Data store ID
     */
    @Location("/data-stores/{dataStoreId}/logs")
    class Logs(val dataStoreId: UUID)


    /**
     * Log stored in [dataStoreId] and specified by [identityId].
     *
     * @param dataStoreId Data store ID
     * @param identityId Log's identity:id attribute value
     */
    @Location("/data-stores/{dataStoreId}/logs/{identityId}")
    class Log(val dataStoreId: UUID, val identityId: UUID)

    /**
     * Data store assigned to [organizationId] and specified by [dataStoreId].
     *
     * @param organizationId Organization ID
     * @param dataStoreId Data store ID
     */
    @Location("/organizations/{organizationId}/data-stores/{dataStoreId}")
    class DataStore(val organizationId: UUID, val dataStoreId: UUID)

    /**
     * Data connectors assigned to [dataStoreId].
     *
     * @param organizationId Organization ID
     * @param dataStoreId Data store ID
     */
    @Location("/organizations/{organizationId}/data-stores/{dataStoreId}/data-connectors")
    class DataConnectors(val organizationId: UUID, val dataStoreId: UUID)

    /**
     * Data connector assigned to [dataStoreId] and specified by [dataConnectorId].
     *
     * @param organizationId Organization ID
     * @param dataStoreId Data store ID
     * @param dataConnectorId Data connector ID
     */
    @Location("/organizations/{organizationId}/data-stores/{dataStoreId}/data-connectors/{dataConnectorId}")
    class DataConnector(val organizationId: UUID, val dataStoreId: UUID, val dataConnectorId: UUID)

    /**
     * Tests connectivity with the specified connection properties.
     *
     * @param organizationId Organization ID
     * @param dataStoreId Data store ID
     */
    @Location("/organizations/{organizationId}/data-stores/{dataStoreId}/data-connectors/test")
    class ConnectionTest(val organizationId: UUID, val dataStoreId: UUID)

    /**
     * Case notions related to the specified [dataConnectorId].
     *
     * @param organizationId Organization ID
     * @param dataStoreId Data store ID
     * @param dataConnectorId Data connector ID
     */
    @Location("/organizations/{organizationId}/data-stores/{dataStoreId}/data-connectors/{dataConnectorId}/case-notions")
    class CaseNotionSuggestions(val organizationId: UUID, val dataStoreId: UUID, val dataConnectorId: UUID)


    @Location("/organizations/{organizationId}/data-stores/{dataStoreId}/data-connectors/{dataConnectorId}/relationship-graph")
    class RelationshipGraph(val organizationId: UUID, val dataStoreId: UUID, val dataConnectorId: UUID)

    /**
     * ETL processes assigned to [dataStoreId].
     *
     * @param organizationId Organization ID
     * @param dataStoreId Data store ID
     */
    @Location("/organizations/{organizationId}/data-stores/{dataStoreId}/etl-processes")
    class EtlProcesses(val organizationId: UUID, val dataStoreId: UUID)

    /**
     * ETL process assigned to [dataStoreId] and specified by [etlProcessId].
     *
     * @param organizationId Organization ID
     * @param dataStoreId Data store ID
     * @param etlProcessId Data connector ID
     */
    @Location("/organizations/{organizationId}/data-stores/{dataStoreId}/etl-processes/{etlProcessId}")
    class EtlProcess(val organizationId: UUID, val dataStoreId: UUID, val etlProcessId: UUID)


    /**
     * XES log obtained from ETL process specified by [etlProcessId] and assigned to [dataStoreId].
     *
     * @param organizationId Organization ID
     * @param dataStoreId Data store ID
     * @param etlProcessId Data connector ID
     */
    @Location("/organizations/{organizationId}/data-stores/{dataStoreId}/etl-processes/{etlProcessId}/logs")
    class EtlProcessLog(val organizationId: UUID, val dataStoreId: UUID, val etlProcessId: UUID)
    
    @Location("/organizations/{organizationId}/data-stores/{dataStoreId}/sampling-etl-processes/")
    class SamplingEtlProcess(val organizationId: UUID, val dataStoreId: UUID, val nComponents: Int?=null)

    /**
     * Get details about current user
     *
     */
    @Location("/users/me")
    class UserAccountDetails

    /**
     * Get organizations which the current user is a member of
     *
     */
    @Location("/users/me/organizations")
    class UserOrganizations

    /**
     * Get organizations which the current user is a member of
     *
     */
    @Location("/users")
    class Users

    /**
     * Get users associated with the current user by organization membership
     *
     */
    @Location("/users/session")
    class UsersSession

    /**
     * Get, update or remove the specified workspace in the context of the specified organization
     *
     * @param organizationId Organization ID
     * @param workspaceId Workspace ID
     */
    @Location("/organizations/{organizationId}/workspaces/{workspaceId}")
    class Workspace(val organizationId: UUID, val workspaceId: UUID)

    /**
     * Get or update the specified component in the specified workspace in the context of the specified organization
     *
     * @param organizationId Organization ID
     * @param workspaceId Workspace ID
     * @param componentId Component ID
     */
    @Location("/organizations/{organizationId}/workspaces/{workspaceId}/components/{componentId}")
    class WorkspaceComponent(val organizationId: UUID, val workspaceId: UUID, val componentId: UUID)

    /**
     * Get data of the specified component in the specified workspace in the context of the specified organization
     *
     * @param organizationId Organization ID
     * @param workspaceId Workspace ID
     * @param componentId Component ID
     */
    @Location("/organizations/{organizationId}/workspaces/{workspaceId}/components/{componentId}/data")
    class WorkspaceComponentData(val organizationId: UUID, val workspaceId: UUID, val componentId: UUID)

    /**
     * Get all components available to the calling user in the specified workspace in the context of the specified organization
     *
     * @param organizationId Organization ID
     * @param workspaceId Workspace ID
     */
    @Location("/organizations/{organizationId}/workspaces/{workspaceId}/components")
    class WorkspaceComponents(val organizationId: UUID, val workspaceId: UUID)

    /**
     * Update size and position of the specified components
     *
     * @param organizationId Organization ID
     * @param workspaceId Workspace ID
     */
    @Location("/organizations/{organizationId}/workspaces/{workspaceId}/layout")
    class WorkspaceLayout(val organizationId: UUID, val workspaceId: UUID)

    /**
     * Get all workspaces available to the calling user in the context of the specified organization
     *
     * @param organizationId Organization ID
     */
    @Location("/organizations/{organizationId}/workspaces")
    class Workspaces(val organizationId: UUID)

}
