package processm.services.helpers

import io.ktor.http.*

enum class ExceptionReason(val statusCode: HttpStatusCode = HttpStatusCode.BadRequest) {
    UnspecifiedReason,
    NoFieldInToken,
    NotAMemberOfOrganization(HttpStatusCode.Forbidden),
    InsufficientPermissionInOrganization(HttpStatusCode.Forbidden),
    UnparsableData,
    LastACECannotBeDowngraded(HttpStatusCode.UnprocessableEntity),
    ACENotFound(HttpStatusCode.NotFound),
    LastACECannotBeRemoved(HttpStatusCode.UnprocessableEntity),
    ACLCannotBeModified(HttpStatusCode.Forbidden),
    ACLCannotBeRead(HttpStatusCode.Forbidden),
    InvalidUsernameOrPassword(HttpStatusCode.Unauthorized),

    @Deprecated("In principle this error should not happen. It is left just in case.")
    PQLError,

    UnexpectedRequestParameter,
    InvalidFile,
    UnsupportedContentType,
    ConnectorConfigurationRequired,
    ConnectorNameRequired,
    DataStoreNameRequired,
    ConnectorReferenceRequired,
    ETLProcessNameRequired,
    EmptyETLConfigurationNotSupported,
    ETLProcessTypeNotSupported,
    ActivationStatusRequired,
    NotFound(HttpStatusCode.NotFound),
    TokenExpired(HttpStatusCode.Unauthorized),
    CredentialsOrTokenRequired,
    WorkspaceNameRequired,
    ConnectionTestFailed,
    InvalidTokenFormat(HttpStatusCode.Unauthorized),
    ParentOrganizationAlreadySet,
    InvalidUserID,
    OrganizationNotFound(HttpStatusCode.NotFound),
    OrganizationAlreadyTopLevel(HttpStatusCode.UnprocessableEntity),
    UserNotFound(HttpStatusCode.NotFound),
    GroupNotFound(HttpStatusCode.NotFound),
    UserNotFoundInOrganization(HttpStatusCode.NotFound),
    DataStoreRequired,
    ComponentTypeRequired,
    QueryRequired,
    SharedGroupNotAssigned(HttpStatusCode.NotFound),
    WorkspaceNotFound(HttpStatusCode.NotFound),
    WorkspaceComponentNotFound(HttpStatusCode.NotFound),
    SoleOwner(HttpStatusCode.UnprocessableEntity),
    BlankName,
    InvalidGroupSpecification,
    CannotDetachFromSharedGroup,
    CannotDetachFromImplicitGroup,
    UserOrGroupNotFound(HttpStatusCode.NotFound),
    OrganizationCannotBeItsOwnChild,
    AlreadyDescendant,
    UserAlreadyInOrganization(HttpStatusCode.Conflict),
    NotADirectSuborganization,
    CannotChangeRole(HttpStatusCode.UnprocessableEntity),
    CannotDelete(HttpStatusCode.UnprocessableEntity),
    InvalidLocale,
    CannotChangeLocale,
    InvalidEmail,
    PasswordTooWeak,
    UserAlreadyExists(HttpStatusCode.Conflict),
    InsufficientPermissionToURN(HttpStatusCode.Forbidden),
    DataStoreNotFound(HttpStatusCode.NotFound),
    ETLProcessNotFound(HttpStatusCode.NotFound)
}

